name: learn github action

on:
    push: 
        branches:
            - main
    workflow_dispatch:

jobs:

    myfirstjob:
        runs-on: ubuntu-latest
        steps:
            - name: clone my repository
              run: echo "I am learning DevOps"

    mysecondjob:
        runs-on: ubentu-latest
        steps:
            - name: learn github action step
              run:  echo "this is my secondjob"        
          
